name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.PMAK-6596eb7aa7ee39003f6ffad5-668595021b344321153fdad56f2d44c903 }}
      - name: Run API tests
        run: |
          postman collection run "27898693-aa272ff5-b3d4-4bda-aab7-8d822123362f"
          # Lint your API using Postman CLI
          postman api lint 0fdd3b3d-11e3-47d3-8dd9-9956f6f22c49
